// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluksof91LrkpyEJc9NSofzvN5GQh7mBA',
    appId: '1:1071626516951:web:69740001f5b2f2642af392',
    messagingSenderId: '1071626516951',
    projectId: 'managementsystem-3c2ca',
    authDomain: 'managementsystem-3c2ca.firebaseapp.com',
    storageBucket: 'managementsystem-3c2ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbx3r6K4qFxOSrXWIIYAABi03msYNNteE',
    appId: '1:1071626516951:android:ff945f4bb79fa49b2af392',
    messagingSenderId: '1071626516951',
    projectId: 'managementsystem-3c2ca',
    storageBucket: 'managementsystem-3c2ca.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluksof91LrkpyEJc9NSofzvN5GQh7mBA',
    appId: '1:1071626516951:web:d6efc1625a1e1fb82af392',
    messagingSenderId: '1071626516951',
    projectId: 'managementsystem-3c2ca',
    authDomain: 'managementsystem-3c2ca.firebaseapp.com',
    storageBucket: 'managementsystem-3c2ca.appspot.com',
  );
}
